<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>8b7a4607-4e43-4930-b70e-37550ed87c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='prelim-details']/div/div/div[2]/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .card > .card-body > a:nth-child(7) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6702b647-604d-4b9c-80a6-875ee9ac0832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cce_2019/CCEP_GS_2022_2.pdf</value>
      <webElementGuid>0082402a-4921-491b-99d7-186a018d1317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>e5752920-032b-42e1-8239-518e5031b0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/section[@id=&quot;prelim-details&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row py-1&quot;]/div[@class=&quot;col-lg-4 col-md-6 pb-3&quot;]/div[@class=&quot;card author-details border-info&quot;]/div[@class=&quot;card-body&quot;]/a[2]</value>
      <webElementGuid>ee52f290-dcdb-4428-a49a-74c574cddc77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='prelim-details']/div/div/div[2]/div/div[2]/a[2]</value>
      <webElementGuid>f5f1c41d-2638-4ada-9edc-1404ab3e1ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[4]</value>
      <webElementGuid>d6efd2ec-6fe6-448e-8703-7e448b6b39ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Studies-II'])[3]/following::a[1]</value>
      <webElementGuid>a0d85693-5562-400f-801f-ff6fca0d3693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[3]/following::a[1]</value>
      <webElementGuid>25dbb362-1785-4636-b763-5dc303299b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC(P)E-2023 Questions'])[1]/preceding::a[1]</value>
      <webElementGuid>52a83fc0-bd94-4999-8f19-c899b683d403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cce_2019/CCEP_GS_2022_2.pdf')]</value>
      <webElementGuid>e963dc1e-6a0e-40a7-b51b-98d85f1f1ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a[2]</value>
      <webElementGuid>056a2847-8b0f-4e30-a89f-847768a49a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cce_2019/CCEP_GS_2022_2.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>400256fe-175c-4519-b54e-e5f4bcce022a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
