<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download_1</name>
   <tag></tag>
   <elementGuidId>a4f3df07-c6b4-4c8f-b366-58a61771d3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-body > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='prelim-details']/div/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card-body > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b8eeca3-c8c3-4603-9764-31a6732050cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cce_2019/Syllabus_CCE(P)_GS_I.pdf</value>
      <webElementGuid>e7664863-bbe5-4c19-b1e5-d71185aa1de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>bc73c22d-2b2a-48cc-b3cb-33b8b2424487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/section[@id=&quot;prelim-details&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row py-1&quot;]/div[@class=&quot;col-lg-4 col-md-6 pb-3&quot;]/div[@class=&quot;card author-details border-info&quot;]/div[@class=&quot;card-body&quot;]/a[1]</value>
      <webElementGuid>82ddc653-100b-4ffe-ac04-cfb692db9764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='prelim-details']/div/div/div/div/div[2]/a</value>
      <webElementGuid>56be587f-0d1e-47f0-9c73-0477a662ed17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>6b046b43-120f-4861-9f4a-efbcd57ee757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Studies-I'])[2]/following::a[1]</value>
      <webElementGuid>6a9ac7ef-c6be-4abe-8316-93b3e1719d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syllabus'])[1]/following::a[1]</value>
      <webElementGuid>55e3ec5f-b8b8-412f-8bb1-9c8ec28d53bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Studies-II'])[2]/preceding::a[1]</value>
      <webElementGuid>4fde076f-5fd6-429a-8a4f-6c332979b0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/preceding::a[1]</value>
      <webElementGuid>d9bb7db9-0cb9-4a02-89b5-9a4a16796f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>faf8349b-cbcf-4fa0-9225-e755818fbcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'cce_2019/Syllabus_CCE(P)_GS_I.pdf')]</value>
      <webElementGuid>667629c2-20a4-40d0-a3e6-d239c6e1112c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c65d503f-e093-4504-9d3c-dfc89bfc0dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cce_2019/Syllabus_CCE(P)_GS_I.pdf' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>4a0cd792-9be6-4c99-93a1-bd4d2f310cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
