<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Read More_fas fa-arrow-right</name>
   <tag></tag>
   <elementGuidId>9679bfa3-7a66-453d-b258-17f08096c6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-arrow-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='show_button']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Read More &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c8417274-94a6-499a-afaf-6e04fc4fd8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-arrow-right</value>
      <webElementGuid>4073fbe4-a142-4c0e-ac4c-d167a0a91011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_button&quot;)/i[@class=&quot;fas fa-arrow-right&quot;]</value>
      <webElementGuid>92bd2a55-522f-41e8-9f58-ea64a680ec57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='show_button']/i</value>
      <webElementGuid>d4c990c5-abb5-4cf7-9098-a8336e8d8c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>678d81f9-90fa-4819-9447-15d4fc20832d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
