<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Photo Gallery_latest_advt_marq</name>
   <tag></tag>
   <elementGuidId>d81fd136-23fc-4c53-a506-46cb545c510f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#latest_advt_marq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='latest_advt_marq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#latest_advt_marq</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>677941e4-a32d-4425-ae29-e8b2ae2f749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-body</value>
      <webElementGuid>b76b1d4d-4dbc-499c-92db-e04f4e653e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>latest_advt_marq</value>
      <webElementGuid>216dfdcf-c962-48a4-9b20-c48f4d26a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;latest_advt_marq&quot;)</value>
      <webElementGuid>b1e4f14f-2e38-49db-908a-cd64ac8fd524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='latest_advt_marq']</value>
      <webElementGuid>06211d71-b10c-4153-b93e-48c0f751e420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='latest-advt']/div/ul/div</value>
      <webElementGuid>29785d94-7c48-4650-8d52-525e1e804836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Gallery'])[1]/following::div[3]</value>
      <webElementGuid>23abb560-aec5-48d3-abf3-f7cef84c673c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Results'])[1]/following::div[3]</value>
      <webElementGuid>46f85b2e-93d1-4e47-8139-19208dcc4a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICATION'])[1]/preceding::div[1]</value>
      <webElementGuid>09944919-6829-476e-a0b6-e7b8a7b8e0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div</value>
      <webElementGuid>f7158a9f-25df-48ca-bf67-91ca589c24ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'latest_advt_marq']</value>
      <webElementGuid>fa21fef7-f427-4603-a67a-a560237334bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
