<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Photo Gallery_hover-shadow cursor_1</name>
   <tag></tag>
   <elementGuidId>7125304a-2ce4-486f-8bbd-be2b4e8ce24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='openModal();currentSlide(2)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .hover-shadow >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>29c0ca69-5fd8-41bb-a111-dfb313a46d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/DigiLab2.jpg</value>
      <webElementGuid>18a08ad5-e462-4563-9506-ae3b44c6ccc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openModal();currentSlide(2)</value>
      <webElementGuid>6760eb1e-e5e1-45f1-91cb-5928119a1080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-shadow cursor</value>
      <webElementGuid>350daa72-141c-4aed-84e2-c13a60cd3cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;latest-updates&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column&quot;]/img[@class=&quot;hover-shadow cursor&quot;]</value>
      <webElementGuid>e5846b08-72ae-483b-b9ea-6f841c455c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='openModal();currentSlide(2)']</value>
      <webElementGuid>f9d6fabe-fa01-4dcb-820d-d7adebcb900c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='latest-updates']/div/div[2]/img</value>
      <webElementGuid>d1e82a06-4e9d-4748-a3f8-44c390d39a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>a85b2594-9285-4c13-bc03-c8dd794f8803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/DigiLab2.jpg']</value>
      <webElementGuid>2436034f-ded0-419f-9062-4c886e79090f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
