<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Photo Gallery_hover-shadow cursor</name>
   <tag></tag>
   <elementGuidId>56b94d13-c3d8-4e4d-8b12-cc210f7d86d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hover-shadow.cursor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='openModal();currentSlide(1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.hover-shadow >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f6e474fd-aff6-4170-8a09-7e48c91ce881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/DigiLab1.jpg</value>
      <webElementGuid>a93cb0c0-443c-4e85-b694-71fb8df4c8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openModal();currentSlide(1)</value>
      <webElementGuid>79720d88-49d5-4385-a65e-9fbab86eca43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-shadow cursor</value>
      <webElementGuid>383536b9-6260-4edb-809a-f5db126c3731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;latest-updates&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column&quot;]/img[@class=&quot;hover-shadow cursor&quot;]</value>
      <webElementGuid>79515393-75f9-4033-a60b-d0901a9b15e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='openModal();currentSlide(1)']</value>
      <webElementGuid>d8ca28f6-bc16-4805-a398-2be7dc318695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='latest-updates']/div/div/img</value>
      <webElementGuid>11252d56-462c-4575-b926-a017c4dfe0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>8af80af3-f24b-4328-a50e-c23805ffb40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/DigiLab1.jpg']</value>
      <webElementGuid>56e8a371-f4e7-455e-b8c4-02b9c08b1cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
